CREATE TABLE `Funcionarios` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`rg` VARCHAR(20) NULL DEFAULT NULL,
	`nome` VARCHAR(100) NULL DEFAULT NULL,
	`dataAdmissao` VARCHAR(10) NULL DEFAULT NULL,
	`salario` VARCHAR(20) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
	);